  CREATE TABLE "CHAT_MESSAGES" 
   (	"MSG_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"CONV_ID" NUMBER, 
	"SENDER" VARCHAR2(100), 
	"MESSAGE" CLOB, 
	"SENT_AT" DATE DEFAULT SYSDATE, 
	"IS_READ" CHAR(1) DEFAULT 'N', 
	 PRIMARY KEY ("MSG_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "CLINIC_INFO" 
   (	"CLINIC_ID" NUMBER, 
	"CLINIC_NAME" VARCHAR2(200) CONSTRAINT "CLINIC_NAME_NN" NOT NULL ENABLE, 
	"PHONE_NO" VARCHAR2(15), 
	"MOBILE_NO" VARCHAR2(15), 
	"WEBSITE" VARCHAR2(100), 
	"EMAIL" VARCHAR2(100), 
	"ADDRESS" VARCHAR2(500), 
	"REGISTRATION_NO" VARCHAR2(15), 
	"CLINIC_IMAGE" BLOB, 
	"MIMETYPE" VARCHAR2(255), 
	"FILENAME" VARCHAR2(400), 
	"IMAGE_LAST_UPDATE" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	"NOTE" VARCHAR2(500), 
	"STATUS" VARCHAR2(1) DEFAULT 'Y', 
	"INSERT_BY" VARCHAR2(100), 
	"INSERT_DATE" DATE DEFAULT SYSDATE, 
	"UPDATE_BY" VARCHAR2(100), 
	"UPDATE_DATE" DATE, 
	"DIV_NO" NUMBER, 
	"DIST_NO" NUMBER, 
	"PS_UPAZILA_NO" NUMBER, 
	"UNION_NO" NUMBER, 
	 CONSTRAINT "CI_ID_PK" PRIMARY KEY ("CLINIC_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "DOCTORS_INFO" 
   (	"DOC_ID" NUMBER, 
	"DOC_NAME" VARCHAR2(200) CONSTRAINT "DOC_NAME_NN" NOT NULL ENABLE, 
	"DOC_DOB" DATE, 
	"DG_ID" NUMBER, 
	"DEPT_ID" NUMBER, 
	"MOBILE_NO" VARCHAR2(15), 
	"EMAIL" VARCHAR2(100), 
	"NID_NO" VARCHAR2(20), 
	"JOIN_DATE" DATE, 
	"REGISTRATION_NO" NUMBER, 
	"RESIGN_DATE" DATE, 
	"ADDRESS" VARCHAR2(500), 
	"SPECIALIZATION" VARCHAR2(200), 
	"DOC_IMAGE" BLOB, 
	"MIMETYPE" VARCHAR2(255), 
	"FILENAME" VARCHAR2(400), 
	"IMAGE_LAST_UPDATE" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	"STATUS" VARCHAR2(1) DEFAULT 'Y', 
	"INSERT_BY" VARCHAR2(100), 
	"INSERT_DATE" DATE DEFAULT SYSDATE, 
	"UPDATE_BY" VARCHAR2(100), 
	"UPDATE_DATE" DATE, 
	"DIV_NO" NUMBER, 
	"DIST_NO" NUMBER, 
	"PS_UPAZILA_NO" NUMBER, 
	"UNION_NO" NUMBER, 
	"DR_SH_ID" NUMBER, 
	"DETAILS" VARCHAR2(1000), 
	 CONSTRAINT "DOC_ID_PK" PRIMARY KEY ("DOC_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "MOB_NO_UK" UNIQUE ("MOBILE_NO")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "EMPLOYEES_INFO" 
   (	"EMP_ID" NUMBER, 
	"EMP_NAME" VARCHAR2(200) CONSTRAINT "EMP_NAME_NN" NOT NULL ENABLE, 
	"ADDRESS" VARCHAR2(500), 
	"NID_NO" VARCHAR2(20), 
	"MOBILE_NO" VARCHAR2(15), 
	"EMAIL" VARCHAR2(100), 
	"EMP_HIRE_DATE" DATE, 
	"RESIGN_DATE" DATE, 
	"EMP_IMAGE" BLOB, 
	"MIMETYPE" VARCHAR2(255), 
	"FILENAME" VARCHAR2(400), 
	"IMAGE_LAST_UPDATE" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	"DEPT_ID" NUMBER, 
	"DG_ID" NUMBER, 
	"SALARY" NUMBER, 
	"STATUS" VARCHAR2(1) DEFAULT 'Y', 
	"INSERT_BY" VARCHAR2(100), 
	"INSERT_DATE" DATE DEFAULT SYSDATE, 
	"UPDATE_BY" VARCHAR2(100), 
	"UPDATE_DATE" DATE, 
	"DIV_NO" NUMBER, 
	"DIST_NO" NUMBER, 
	"PS_UPAZILA_NO" NUMBER, 
	"UNION_NO" NUMBER, 
	 CONSTRAINT "EMP_ID_PK" PRIMARY KEY ("EMP_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "MOBILE_NO_UK" UNIQUE ("MOBILE_NO")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "GUSER" 
   (	"USER_ID" VARCHAR2(15), 
	"EMP_ID" NUMBER, 
	"USER_NAME" VARCHAR2(25), 
	"USER_PASS" VARCHAR2(10), 
	"ACTIVE_FLAG" VARCHAR2(1), 
	"COMPANY_ID" NUMBER, 
	"CREATE_BY" VARCHAR2(16), 
	"CREATE_DATE" DATE, 
	"UPDATE_BY" VARCHAR2(16), 
	"UPDATE_DATE" DATE, 
	"PHOTO" BLOB, 
	"MIMETYPE" VARCHAR2(100), 
	"FILENAME" VARCHAR2(100), 
	"EMAIL" VARCHAR2(100)
   ) ;

  CREATE TABLE "ADVICE_INFO" 
   (	"ADV_ID" NUMBER, 
	"ADV_NAME" VARCHAR2(100), 
	"STATUS" VARCHAR2(1) DEFAULT 'Y', 
	"INSERT_BY" VARCHAR2(100), 
	"INSERT_DATE" DATE DEFAULT SYSDATE, 
	"UPDATE_BY" VARCHAR2(100), 
	"UPDATE_DATE" DATE, 
	 CONSTRAINT "ADVV_ID_PK" PRIMARY KEY ("ADV_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "APPOINTMENT_INFO" 
   (	"APP_ID" NUMBER, 
	"APP_DATE_TIME" DATE, 
	"APP_SERIAL_NO" NUMBER, 
	"P_REG_ID" NUMBER, 
	"DOC_SH_ID" NUMBER, 
	"APP_MOBILE_NO" VARCHAR2(15), 
	"RESCHEDULE" DATE, 
	"PATIENT_TYPE" VARCHAR2(100), 
	"SERIAL_NO" NUMBER, 
	"NOTE" VARCHAR2(500), 
	"STATUS" VARCHAR2(1) DEFAULT 'Y', 
	"INSERT_BY" VARCHAR2(100), 
	"INSERT_DATE" DATE DEFAULT SYSDATE, 
	"UPDATE_BY" VARCHAR2(100), 
	"UPDATE_DATE" DATE, 
	"DOC_ID" NUMBER, 
	"DEPT_ID" NUMBER, 
	 CONSTRAINT "APP_ID_PK" PRIMARY KEY ("APP_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "APP_SYS_NAV" 
   (	"NAV_NO" NUMBER(30,0), 
	"NAV_ID" VARCHAR2(30), 
	"NAV_NAME" VARCHAR2(120), 
	"NAV_DESC" VARCHAR2(360), 
	"NAV_URL" VARCHAR2(980), 
	"PAGE_ID" VARCHAR2(30), 
	"PAGE_GROUP" VARCHAR2(180), 
	"NAV_GROUP" VARCHAR2(180), 
	"APP_ID" VARCHAR2(30), 
	"IS_MODAL" NUMBER(1,0) DEFAULT 0, 
	"IS_NAV" NUMBER(1,0) DEFAULT 0, 
	"IS_VIEW" NUMBER(1,0) DEFAULT 1, 
	"HEAD_NO" NUMBER(30,0), 
	"SYS_ICON" VARCHAR2(100), 
	"ORDER_BY" NUMBER(20,0), 
	"REMARKS" VARCHAR2(4000), 
	"STATUS" NUMBER(1,0) DEFAULT 1, 
	"APP_NO" VARCHAR2(1000) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_ID'),SYS_CONTEXT('USERENV','CLIENT_PROGRAM_NAME')), 
	"CREATED_BY" VARCHAR2(200) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_USER'), SYS_CONTEXT('USERENV','OS_USER')), 
	"CREATED_DT" DATE DEFAULT SYSDATE, 
	"CREATED_SN" VARCHAR2(200) DEFAULT NVL(SYS_CONTEXT('APEX$SESSION','APP_SESSION'),SYS_CONTEXT('USERENV','SID')), 
	"UPDATED_BY" VARCHAR2(200), 
	"UPDATED_DT" DATE, 
	"UPDATED_SN" VARCHAR2(200), 
	 CONSTRAINT "APP_SYS_NAV_PK" PRIMARY KEY ("NAV_NO")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "APP_USERS" 
   (	"USER_NO" NUMBER, 
	"USERNAME" VARCHAR2(100), 
	"PWD" VARCHAR2(100), 
	"IS_ACTIVE" VARCHAR2(1), 
	"USER_ROLE" NUMBER, 
	"REG_ID" NUMBER, 
	 PRIMARY KEY ("USER_NO")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "APP_USER_OTP" 
   (	"OTP_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"USERNAME" VARCHAR2(100), 
	"OTP_CODE" VARCHAR2(6), 
	"EXPIRE_AT" DATE, 
	"IS_USED" VARCHAR2(1) DEFAULT 'N', 
	 PRIMARY KEY ("OTP_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "BILLING" 
   (	"BILL_ID" NUMBER, 
	"BILL_DATE" DATE, 
	"SERVICE_ID" NUMBER, 
	"QUANTIY" NUMBER, 
	"DISCOUNT_PCT" NUMBER, 
	"NET_AMOUNT" NUMBER, 
	"APP_ID" NUMBER, 
	"NURSE_ST_ID" NUMBER, 
	"STATUS" VARCHAR2(1) DEFAULT 'Y', 
	"INSERT_BY" VARCHAR2(100), 
	"INSERT_DATE" DATE DEFAULT SYSDATE, 
	"UPDATE_BY" VARCHAR2(100), 
	"UPDATE_DATE" DATE, 
	"DOC_ID" NUMBER, 
	"TOTAL" NUMBER, 
	"DISC_AMT" NUMBER, 
	"RECEIVED_AMT" NUMBER, 
	"DUE_RETURN_AMT" NUMBER, 
	 CONSTRAINT "BILLING_ID_PK" PRIMARY KEY ("BILL_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "CHAT_CONVERSATIONS" 
   (	"CONV_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"CREATED_ON" DATE DEFAULT SYSDATE, 
	 PRIMARY KEY ("CONV_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "CHAT_PARTICIPANTS" 
   (	"CONV_ID" NUMBER, 
	"USERNAME" VARCHAR2(100), 
	 CONSTRAINT "PK_CHAT_PARTICIPANTS" PRIMARY KEY ("CONV_ID", "USERNAME") DISABLE
   ) ;

  CREATE TABLE "CONSULTATION" 
   (	"CONSULTATION_ID" NUMBER, 
	"FOLLOW_UP_DAYS" VARCHAR2(10), 
	"ASSESSMENT_ID" NUMBER, 
	"NOTE" VARCHAR2(500), 
	"STATUS" VARCHAR2(1) DEFAULT 'Y', 
	"INSERT_BY" VARCHAR2(100), 
	"INSERT_DATE" DATE DEFAULT SYSDATE, 
	"UPDATE_BY" VARCHAR2(100), 
	"UPDATE_DATE" DATE, 
	"P_REG_ID" NUMBER, 
	"NURSE_ST_ID" NUMBER, 
	"DOC_ID" NUMBER, 
	"APP_ID" NUMBER, 
	 CONSTRAINT "CONSULT_ID_PK" PRIMARY KEY ("CONSULTATION_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "ASSESS_ID_CONS_UQ" UNIQUE ("ASSESSMENT_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "CONSULT_DTL" 
   (	"CONSULT_DTL_ID" NUMBER, 
	"CONSULTATION_ID" NUMBER, 
	"DIAGNOSIS" VARCHAR2(500), 
	"MEDICAL_HISTORY" VARCHAR2(500), 
	"DRUG_HISTORY" VARCHAR2(500), 
	 CONSTRAINT "CONS_DTL_PK" PRIMARY KEY ("CONSULT_DTL_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "CONSULT_INV_DETAILS" 
   (	"CONSULT_INV_DTL_ID" NUMBER, 
	"CONSULT_INV_DETAILS_REMARKS" VARCHAR2(200), 
	"INV_ID" NUMBER, 
	"CONSULTATION_ID" NUMBER, 
	"STATUS" VARCHAR2(1) DEFAULT 'Y', 
	"INSERT_BY" VARCHAR2(100), 
	"INSERT_DATE" DATE DEFAULT SYSDATE, 
	"UPDATE_BY" VARCHAR2(100), 
	"UPDATE_DATE" DATE, 
	"SL_NO" NUMBER, 
	 CONSTRAINT "PRES_INV_DE_ID_PK" PRIMARY KEY ("CONSULT_INV_DTL_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "CONSULT_MEDICINE_DETAILS" 
   (	"MED_DETAIL_ID" NUMBER, 
	"INTAKE_DAYS" VARCHAR2(50), 
	"MED_ID" NUMBER, 
	"CONSULTATION_ID" NUMBER, 
	"FREQUENCY" VARCHAR2(100), 
	"STATUS" VARCHAR2(1) DEFAULT 'Y', 
	"INSERT_BY" VARCHAR2(100), 
	"INSERT_DATE" DATE DEFAULT SYSDATE, 
	"UPDATE_BY" VARCHAR2(100), 
	"UPDATE_DATE" DATE, 
	"SL_NO" NUMBER, 
	"TIME" VARCHAR2(200), 
	 CONSTRAINT "MED_DET_ID_PK" PRIMARY KEY ("MED_DETAIL_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "CONS_ADVICE_DETAILS" 
   (	"CONSULT_ADV_DTL_ID" NUMBER, 
	"CONSULT_ADV_DETAILS_REMARKS" VARCHAR2(200), 
	"ADV_ID" NUMBER, 
	"CONSULTATION_ID" NUMBER, 
	"STATUS" VARCHAR2(1) DEFAULT 'Y', 
	"INSERT_BY" VARCHAR2(100), 
	"INSERT_DATE" DATE DEFAULT SYSDATE, 
	"UPDATE_BY" VARCHAR2(100), 
	"UPDATE_DATE" DATE, 
	"SL_NO" NUMBER, 
	 CONSTRAINT "CONS_ADV_DTL_ID_PK" PRIMARY KEY ("CONSULT_ADV_DTL_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "DEPARTMENTS_INFO" 
   (	"DEPT_ID" NUMBER, 
	"DEPT_NAME" VARCHAR2(200) CONSTRAINT "DEPT_ID_NN" NOT NULL ENABLE, 
	"DEPT_SHORT_NAME" VARCHAR2(50), 
	"DEPT_MOB_NUMBER" VARCHAR2(15), 
	"DEPT_EMAIL" VARCHAR2(100), 
	"NOTE" VARCHAR2(500), 
	"STATUS" VARCHAR2(1) DEFAULT 'Y', 
	"INSERT_BY" VARCHAR2(100), 
	"INSERT_DATE" DATE DEFAULT SYSDATE, 
	"UPDATE_BY" VARCHAR2(100), 
	"UPDATE_DATE" DATE, 
	 CONSTRAINT "DEPT_ID_PK" PRIMARY KEY ("DEPT_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "DESIGNATIONS_INFO" 
   (	"DG_ID" NUMBER, 
	"DG_NAME" VARCHAR2(200) CONSTRAINT "DG_NAME_NN" NOT NULL ENABLE, 
	"NOTE" VARCHAR2(500), 
	"STATUS" VARCHAR2(1) DEFAULT 'Y', 
	"INSERT_BY" VARCHAR2(100), 
	"INSERT_DATE" DATE DEFAULT SYSDATE, 
	"UPDATE_BY" VARCHAR2(100), 
	"UPDATE_DATE" DATE, 
	 CONSTRAINT "DG_ID_PK" PRIMARY KEY ("DG_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "DISEASE" 
   (	"DIS_ID" NUMBER, 
	"DISEASE_NAME" VARCHAR2(200), 
	 CONSTRAINT "DISEASE_PK" PRIMARY KEY ("DIS_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "DISEASE_MEDICINE" 
   (	"DISEASE_MED_ID" NUMBER, 
	"DIS_ID" NUMBER NOT NULL ENABLE, 
	"MED_ID" NUMBER NOT NULL ENABLE, 
	"FREQUENCY" VARCHAR2(50), 
	"INTAKE_DAYS" NUMBER, 
	 PRIMARY KEY ("DISEASE_MED_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "DISTRICTS" 
   (	"DIST_NO" NUMBER, 
	"DIV_NO" NUMBER, 
	"DIST_NAME" VARCHAR2(100), 
	 CONSTRAINT "DIST_NO_PK" PRIMARY KEY ("DIST_NO")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "DISTRICTS_ERR$" 
   (	"ORA_ERR_NUMBER$" NUMBER, 
	"ORA_ERR_MESG$" VARCHAR2(2000), 
	"ORA_ERR_ROWID$" UROWID (4000), 
	"ORA_ERR_OPTYP$" VARCHAR2(2), 
	"ORA_ERR_TAG$" VARCHAR2(2000), 
	"DIST_NO" VARCHAR2(4000), 
	"DIV_NO" VARCHAR2(4000), 
	"DIST_NAME" VARCHAR2(4000)
   ) ;

  CREATE TABLE "DIVISIONS" 
   (	"DIV_NO" NUMBER, 
	"DIV_NAME" VARCHAR2(100), 
	 CONSTRAINT "DIV_NO_PK" PRIMARY KEY ("DIV_NO")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "DOCS_AV_DAY" 
   (	"DOC_DAYS" NUMBER, 
	"DOC_ID" NUMBER, 
	"SAT" NUMBER(1,0), 
	"SUN" NUMBER(1,0), 
	"MON" NUMBER(1,0), 
	"TUE" NUMBER(1,0), 
	"WED" NUMBER(1,0), 
	"THU" NUMBER(1,0), 
	"FRI" NUMBER(1,0), 
	 CONSTRAINT "DOC_DAY_PK" PRIMARY KEY ("DOC_DAYS")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "DOCTORS_DTL_INFO" 
   (	"DTL_ID" NUMBER, 
	"DOC_ID" NUMBER, 
	"DD_ID" NUMBER, 
	"NOTE" VARCHAR2(500), 
	"STATUS" VARCHAR2(1) DEFAULT 'Y', 
	"INSERT_BY" VARCHAR2(100), 
	"INSERT_DATE" DATE DEFAULT SYSDATE, 
	"UPDATE_BY" VARCHAR2(100), 
	"UPDATE_DATE" DATE, 
	"RESULT" VARCHAR2(50), 
	"DURATION" VARCHAR2(50), 
	 CONSTRAINT "DTL_ID_PK" PRIMARY KEY ("DTL_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "DOCTOR_SHIFT_DTL" 
   (	"DOC_SH_ID" NUMBER, 
	"DOC_ID" NUMBER, 
	"SH_ID" NUMBER, 
	"STATUS" VARCHAR2(1) DEFAULT 'Y', 
	"INSERT_BY" VARCHAR2(100), 
	"INSERT_DATE" DATE DEFAULT SYSDATE, 
	"UPDATE_BY" VARCHAR2(100), 
	"UPDATE_DATE" DATE, 
	 CONSTRAINT "DOC_SH_ID_PK" PRIMARY KEY ("DOC_SH_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "DOC_EXP_DTL" 
   (	"DOC_EXP_ID" NUMBER, 
	"DOC_ID" NUMBER, 
	"EXPERIENCE" VARCHAR2(500), 
	"DURATION" VARCHAR2(200), 
	"NOTE" VARCHAR2(500), 
	"STATUS" VARCHAR2(1), 
	"INSERT_BY" VARCHAR2(100), 
	"INSERT_DATE" DATE, 
	"UPDATE_BY" VARCHAR2(100), 
	"UPDATE_DATE" DATE
   ) ;

  CREATE TABLE "DOC_SERVICES" 
   (	"DOC_SERVICE_ID" NUMBER, 
	"DOC_ID" NUMBER, 
	"SERVICE_ID" NUMBER, 
	"RATE" NUMBER, 
	"STATUS" VARCHAR2(1) DEFAULT 'Y', 
	"INSERT_BY" VARCHAR2(100), 
	"INSERT_DATE" DATE DEFAULT SYSDATE, 
	"UPDATE_BY" VARCHAR2(100), 
	"UPDATE_DATE" DATE, 
	"PATIENT_TYPE" VARCHAR2(100), 
	 CONSTRAINT "DOC_SERVICE_PK" PRIMARY KEY ("DOC_SERVICE_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "DR_DEGREES_INFO" 
   (	"DD_ID" NUMBER, 
	"DD_NAME" VARCHAR2(100) CONSTRAINT "DD_NAME_NN" NOT NULL ENABLE, 
	"STATUS" VARCHAR2(1) DEFAULT 'Y', 
	"INSERT_BY" VARCHAR2(100), 
	"INSERT_DATE" DATE DEFAULT SYSDATE, 
	"UPDATE_BY" VARCHAR2(100), 
	"UPDATE_DATE" DATE, 
	 CONSTRAINT "DD_ID_PK" PRIMARY KEY ("DD_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "DR_NEW_SHIFT_INFO" 
   (	"DR_SH_ID" NUMBER, 
	"SHIFT_NAME" VARCHAR2(200), 
	"START_TIME" VARCHAR2(200), 
	"END_TIME" VARCHAR2(200), 
	"NOTE" VARCHAR2(500), 
	"STATUS" VARCHAR2(1), 
	"INSERT_BY" VARCHAR2(100), 
	"INSERT_DATE" DATE, 
	"UPDATE_BY" VARCHAR2(100), 
	"UPDATE_DATE" VARCHAR2(100), 
	 CONSTRAINT "DR_SH_PK_NEW" PRIMARY KEY ("DR_SH_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "EMPLOYEE_SHIFT_DTL" 
   (	"EMP_SH_ID" NUMBER, 
	"EMP_ID" NUMBER, 
	"SH_ID" NUMBER, 
	"STATUS" VARCHAR2(1) DEFAULT 'Y', 
	"INSERT_BY" VARCHAR2(100), 
	"INSERT_DATE" DATE DEFAULT SYSDATE, 
	"UPDATE_BY" VARCHAR2(100), 
	"UPDATE_DATE" DATE, 
	 CONSTRAINT "EMP_SH_ID_PK" PRIMARY KEY ("EMP_SH_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "GENERIC_INFO" 
   (	"GENERIC_ID" NUMBER, 
	"GENERIC_NAME" VARCHAR2(100) CONSTRAINT "GEN_NAME_NN" NOT NULL ENABLE, 
	"NOTE" VARCHAR2(500), 
	"STATUS" VARCHAR2(1) DEFAULT 'Y', 
	"INSERT_BY" VARCHAR2(100), 
	"INSERT_DATE" DATE DEFAULT SYSDATE, 
	"UPDATE_BY" VARCHAR2(100), 
	"UPDATE_DATE" DATE, 
	 CONSTRAINT "GEN_ID_PK" PRIMARY KEY ("GENERIC_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "GROUPS" 
   (	"GROUP_ID" NUMBER, 
	"GROUP_NAME" VARCHAR2(200), 
	"ACTIVE_FLAG" VARCHAR2(1), 
	"COMPANY_ID" NUMBER, 
	"CREATE_BY" VARCHAR2(16), 
	"CREATE_DATE" DATE, 
	"UPDATE_BY" VARCHAR2(16), 
	"UPDATE_DATE" DATE, 
	 CONSTRAINT "GROUP_PK" PRIMARY KEY ("GROUP_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "GROUP_MENU" 
   (	"GROUP_ID" NUMBER, 
	"GROUP_MENU_ID" NUMBER, 
	"MENU_CODE" VARCHAR2(6), 
	"MENU_NAME" VARCHAR2(200), 
	"APEX_PAGE_NO" VARCHAR2(4), 
	"IS_STATUS" NUMBER(1,0), 
	"IS_SELECT" NUMBER(1,0), 
	"IS_UPDATE" NUMBER(1,0), 
	"IS_DELETE" NUMBER(1,0), 
	"COMPANY_ID" NUMBER, 
	"CREATE_BY" VARCHAR2(16), 
	"CREATE_DATE" DATE, 
	"UPDATE_BY" VARCHAR2(16), 
	"UPDATE_DATE" DATE, 
	 CONSTRAINT "GROUP_MENU_ID_PK" PRIMARY KEY ("GROUP_MENU_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "HTMLDB_PLAN_TABLE" 
   (	"STATEMENT_ID" VARCHAR2(30), 
	"PLAN_ID" NUMBER, 
	"TIMESTAMP" DATE, 
	"REMARKS" VARCHAR2(4000), 
	"OPERATION" VARCHAR2(30), 
	"OPTIONS" VARCHAR2(255), 
	"OBJECT_NODE" VARCHAR2(128), 
	"OBJECT_OWNER" VARCHAR2(128), 
	"OBJECT_NAME" VARCHAR2(128), 
	"OBJECT_ALIAS" VARCHAR2(261), 
	"OBJECT_INSTANCE" NUMBER(*,0), 
	"OBJECT_TYPE" VARCHAR2(128), 
	"OPTIMIZER" VARCHAR2(255), 
	"SEARCH_COLUMNS" NUMBER, 
	"ID" NUMBER(*,0), 
	"PARENT_ID" NUMBER(*,0), 
	"DEPTH" NUMBER(*,0), 
	"POSITION" NUMBER(*,0), 
	"COST" NUMBER(*,0), 
	"CARDINALITY" NUMBER(*,0), 
	"BYTES" NUMBER(*,0), 
	"OTHER_TAG" VARCHAR2(255), 
	"PARTITION_START" VARCHAR2(255), 
	"PARTITION_STOP" VARCHAR2(255), 
	"PARTITION_ID" NUMBER(*,0), 
	"OTHER" LONG, 
	"DISTRIBUTION" VARCHAR2(30), 
	"CPU_COST" NUMBER(*,0), 
	"IO_COST" NUMBER(*,0), 
	"TEMP_SPACE" NUMBER(*,0), 
	"ACCESS_PREDICATES" VARCHAR2(4000), 
	"FILTER_PREDICATES" VARCHAR2(4000), 
	"PROJECTION" VARCHAR2(4000), 
	"TIME" NUMBER(*,0), 
	"QBLOCK_NAME" VARCHAR2(128)
   ) ;

  CREATE TABLE "INVESTIGATION_INFO" 
   (	"INV_ID" NUMBER, 
	"INV_NAME" VARCHAR2(100), 
	"STATUS" VARCHAR2(1) DEFAULT 'Y', 
	"INSERT_BY" VARCHAR2(100), 
	"INSERT_DATE" DATE DEFAULT SYSDATE, 
	"UPDATE_BY" VARCHAR2(100), 
	"UPDATE_DATE" DATE, 
	 CONSTRAINT "INV_ID_PK" PRIMARY KEY ("INV_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "MEDICINE_INFO" 
   (	"MED_ID" NUMBER, 
	"MED_NAME" VARCHAR2(200) CONSTRAINT "MC_NAME_NN" NOT NULL ENABLE, 
	"MED_TYPE" VARCHAR2(100), 
	"MED_DESCRIPTION" VARCHAR2(500), 
	"DOSAGE_FORM" VARCHAR2(100), 
	"U_O_M" VARCHAR2(50), 
	"GENERIC_ID" NUMBER, 
	"STATUS" VARCHAR2(1) DEFAULT 'Y', 
	"INSERT_BY" VARCHAR2(100), 
	"INSERT_DATE" DATE DEFAULT SYSDATE, 
	"UPDATE_BY" VARCHAR2(100), 
	"UPDATE_DATE" DATE, 
	 CONSTRAINT "MED_ID_PK" PRIMARY KEY ("MED_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "MENU" 
   (	"MENU_CODE" VARCHAR2(10), 
	"MENU_NAME" VARCHAR2(100), 
	"FORM_NAME" VARCHAR2(100), 
	"DISPLAY_NAME" VARCHAR2(100), 
	"PARENT_MENU" VARCHAR2(10), 
	"APEX_PAGE_NO" VARCHAR2(4), 
	"SUB_APEX_PAGE_NO" VARCHAR2(4), 
	"SUB_FORM_NAME" VARCHAR2(100), 
	"COMPANY_ID" NUMBER, 
	"CREATE_BY" VARCHAR2(16), 
	"CREATE_DATE" DATE, 
	"UPDATE_BY" VARCHAR2(16), 
	"UPDATE_DATE" DATE, 
	 CONSTRAINT "MENU_MENU_CODE_PK" PRIMARY KEY ("MENU_CODE")
  USING INDEX  ENABLE, 
	 CONSTRAINT "MENU_MENU_APEX_MENU_UK" UNIQUE ("MENU_CODE", "APEX_PAGE_NO")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "NURSE_STATION" 
   (	"NURSE_ST_ID" NUMBER, 
	"VISIT_DATE" DATE, 
	"IN_FLAG" VARCHAR2(1), 
	"CONSULT_FLAG" VARCHAR2(1), 
	"BILLING_FLAG" VARCHAR2(1), 
	"OUT_FLAG" VARCHAR2(1), 
	"APP_ID" NUMBER, 
	"STATUS" VARCHAR2(1) DEFAULT 'Y', 
	"INSERT_BY" VARCHAR2(100), 
	"INSERT_DATE" DATE DEFAULT SYSDATE, 
	"UPDATE_BY" VARCHAR2(100), 
	"UPDATE_DATE" DATE, 
	"STATUS_VITAL_SIGN" VARCHAR2(100) DEFAULT 'Not-Done', 
	 CONSTRAINT "NURSE_ST_ID_PK" PRIMARY KEY ("NURSE_ST_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "APP_ID_NU_ST_UQ" UNIQUE ("APP_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "PATIENTS_REG_INFO" 
   (	"P_REG_ID" NUMBER, 
	"P_NAME" VARCHAR2(200) CONSTRAINT "P_NAME_NN" NOT NULL ENABLE, 
	"MOBILE_NO" VARCHAR2(15) NOT NULL ENABLE, 
	"DATE_OF_BIRTH" DATE, 
	"GENDER" VARCHAR2(10), 
	"BLOOD_GROUP" VARCHAR2(3), 
	"EMAIL" VARCHAR2(100), 
	"EMERGENCY_CONTACT_NAME" VARCHAR2(200), 
	"EMERGENCY_CONTACT_RELATION" VARCHAR2(50), 
	"EMERGENCY_CONTACT_NO" VARCHAR2(15), 
	"ADDRESS" VARCHAR2(500), 
	"STATUS" VARCHAR2(1) DEFAULT 'Y', 
	"INSERT_BY" VARCHAR2(100), 
	"INSERT_DATE" DATE DEFAULT SYSDATE, 
	"UPDATE_BY" VARCHAR2(100), 
	"UPDATE_DATE" DATE, 
	"UNION_NO" NUMBER, 
	"DIV_NO" NUMBER, 
	"DIST_NO" NUMBER, 
	"PS_UPAZILA_NO" NUMBER, 
	 CONSTRAINT "P_REG_ID_PK" PRIMARY KEY ("P_REG_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "PRIMARY_ASSESSMENT" 
   (	"ASSESSMENT_ID" NUMBER, 
	"PULSE" VARCHAR2(50), 
	"BP" VARCHAR2(50), 
	"RR" VARCHAR2(50), 
	"H_RATE" VARCHAR2(50), 
	"TEMP" VARCHAR2(50), 
	"HEIGHT" VARCHAR2(50), 
	"WEIGHT" VARCHAR2(50), 
	"CHIEF_COMPLAINS" VARCHAR2(200), 
	"NOTE" VARCHAR2(500), 
	"NURSE_ST_ID" NUMBER, 
	"STATUS" VARCHAR2(1) DEFAULT 'Y', 
	"INSERT_BY" VARCHAR2(100), 
	"INSERT_DATE" DATE DEFAULT SYSDATE, 
	"UPDATE_BY" VARCHAR2(100), 
	"UPDATE_DATE" DATE, 
	 CONSTRAINT "P_A_ID_PK" PRIMARY KEY ("ASSESSMENT_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "NU_ST_IDIN_PR_AS_UQ" UNIQUE ("NURSE_ST_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "PS_UPAZILAS" 
   (	"PS_UPAZILA_NO" NUMBER, 
	"DIST_NO" NUMBER, 
	"PS_UPAZILA_NAME" VARCHAR2(100), 
	 CONSTRAINT "PS_UPAZILA_NO_PK" PRIMARY KEY ("PS_UPAZILA_NO")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "ROLES_INFO" 
   (	"RI_ID" NUMBER, 
	"RI_NAME" VARCHAR2(100) CONSTRAINT "RI_NAME_NN" NOT NULL ENABLE, 
	"STATUS" VARCHAR2(1) DEFAULT 'Y', 
	"INSERT_BY" VARCHAR2(100), 
	"INSERT_DATE" DATE DEFAULT SYSDATE, 
	"UPDATE_BY" VARCHAR2(100), 
	"UPDATE_DATE" DATE, 
	 CONSTRAINT "RI_ID_PK" PRIMARY KEY ("RI_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "SERVICES" 
   (	"SERVICE_ID" NUMBER, 
	"SERVICE_NAME" VARCHAR2(200), 
	"STATUS" VARCHAR2(1) DEFAULT 'Y', 
	"INSERT_BY" VARCHAR2(100), 
	"INSERT_DATE" DATE DEFAULT SYSDATE, 
	"UPDATE_BY" VARCHAR2(100), 
	"UPDATE_DATE" DATE, 
	 CONSTRAINT "SERVICE_ID_PK" PRIMARY KEY ("SERVICE_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "SHIFTS_INFO" 
   (	"SH_ID" NUMBER, 
	"SH_NAME" VARCHAR2(100) CONSTRAINT "SH_NAME_NN" NOT NULL ENABLE, 
	"SH_START_TIME" VARCHAR2(20) CONSTRAINT "SH_START_TIME_NN" NOT NULL ENABLE, 
	"SH_BREAK_START_TIME" VARCHAR2(20), 
	"SH_BREAK_END_TIME" VARCHAR2(20), 
	"SH_END_TIME" VARCHAR2(20) CONSTRAINT "SI_END_TIME_NN" NOT NULL ENABLE, 
	"DAY_NAME" VARCHAR2(50) CONSTRAINT "DA_NAME_NN" NOT NULL ENABLE, 
	"STATUS" VARCHAR2(1) DEFAULT 'Y', 
	"INSERT_BY" VARCHAR2(100), 
	"INSERT_DATE" DATE DEFAULT SYSDATE, 
	"UPDATE_BY" VARCHAR2(100), 
	"UPDATE_DATE" DATE, 
	 CONSTRAINT "SH_ID_PK" PRIMARY KEY ("SH_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "UNIONS" 
   (	"UNION_NO" NUMBER, 
	"PS_UPAZILA_NO" NUMBER, 
	"UNION_NAME" VARCHAR2(100), 
	 CONSTRAINT "UNION_NO_PK" PRIMARY KEY ("UNION_NO")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "USERS_INFO" 
   (	"UI_ID" NUMBER, 
	"USERNAME" VARCHAR2(100), 
	"PASSWORD" VARCHAR2(100) CONSTRAINT "PASSWORD_NN" NOT NULL ENABLE, 
	"EMP_ID" NUMBER, 
	"RI_ID" NUMBER, 
	"STATUS" VARCHAR2(1) DEFAULT 'Y', 
	"INSERT_BY" VARCHAR2(100), 
	"INSERT_DATE" DATE DEFAULT SYSDATE, 
	"UPDATE_BY" VARCHAR2(100), 
	"UPDATE_DATE" DATE, 
	"SECURITY_QUESTION" VARCHAR2(100), 
	"SECURITY_ANSWER" VARCHAR2(100), 
	 CONSTRAINT "UI_ID_PK" PRIMARY KEY ("UI_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "USERNAME_UK" UNIQUE ("USERNAME")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "USER_GROUP" 
   (	"USER_GROUP_ID" NUMBER, 
	"USER_ID" VARCHAR2(15), 
	"GROUP_ID" NUMBER, 
	"ACTIVE_FLAG" VARCHAR2(1), 
	"COMPANY_ID" NUMBER, 
	"CREATE_BY" VARCHAR2(16), 
	"CREATE_DATE" DATE, 
	"UPDATE_BY" VARCHAR2(16), 
	"UPDATE_DATE" DATE, 
	 CONSTRAINT "USER_GROUP_ID_PK" PRIMARY KEY ("USER_GROUP_ID")
  USING INDEX  ENABLE
   ) ;

  CREATE TABLE "USER_SESSION_TRACKING" 
   (	"LOG_NO" NUMBER, 
	"USERNAME" VARCHAR2(100), 
	"LOG_DATE" DATE DEFAULT SYSDATE, 
	"REC_TYPE" VARCHAR2(100), 
	 CONSTRAINT "USER_LOG_NO_PK" PRIMARY KEY ("LOG_NO")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "APPOINTMENT_INFO" ADD CONSTRAINT "DOC_ID_INAPP_FK" FOREIGN KEY ("DOC_ID")
	  REFERENCES "DOCTORS_INFO" ("DOC_ID") ENABLE;
  ALTER TABLE "APPOINTMENT_INFO" ADD CONSTRAINT "DOC_SH_ID_APP_FK" FOREIGN KEY ("DOC_SH_ID")
	  REFERENCES "DOCTOR_SHIFT_DTL" ("DOC_SH_ID") ENABLE;
  ALTER TABLE "APPOINTMENT_INFO" ADD CONSTRAINT "P_REG_ID_APP_FK" FOREIGN KEY ("P_REG_ID")
	  REFERENCES "PATIENTS_REG_INFO" ("P_REG_ID") ENABLE;

  ALTER TABLE "BILLING" ADD CONSTRAINT "APP_ID_IN_BILL_FK" FOREIGN KEY ("APP_ID")
	  REFERENCES "APPOINTMENT_INFO" ("APP_ID") ENABLE;
  ALTER TABLE "BILLING" ADD CONSTRAINT "NURSE_ST_IN_BILL_FK" FOREIGN KEY ("NURSE_ST_ID")
	  REFERENCES "NURSE_STATION" ("NURSE_ST_ID") ENABLE;
  ALTER TABLE "BILLING" ADD CONSTRAINT "SERVICE_ID_IN_BILL_FK" FOREIGN KEY ("SERVICE_ID")
	  REFERENCES "SERVICES" ("SERVICE_ID") ENABLE;
  ALTER TABLE "BILLING" ADD FOREIGN KEY ("DOC_ID")
	  REFERENCES "DOCTORS_INFO" ("DOC_ID") ENABLE;

  ALTER TABLE "CHAT_PARTICIPANTS" ADD CONSTRAINT "FK_CHAT_PARTICIPANTS" FOREIGN KEY ("CONV_ID")
	  REFERENCES "CHAT_CONVERSATIONS" ("CONV_ID") ENABLE;

  ALTER TABLE "CONSULTATION" ADD CONSTRAINT "APP_ID_IN_CONS_FK" FOREIGN KEY ("APP_ID")
	  REFERENCES "APPOINTMENT_INFO" ("APP_ID") ENABLE;
  ALTER TABLE "CONSULTATION" ADD CONSTRAINT "AS_ID_IN_CONS_FK" FOREIGN KEY ("ASSESSMENT_ID")
	  REFERENCES "PRIMARY_ASSESSMENT" ("ASSESSMENT_ID") ENABLE;
  ALTER TABLE "CONSULTATION" ADD CONSTRAINT "DOC_ID_INCONS_FK" FOREIGN KEY ("DOC_ID")
	  REFERENCES "DOCTORS_INFO" ("DOC_ID") ENABLE;
  ALTER TABLE "CONSULTATION" ADD CONSTRAINT "NURSE_ST_IN_CONS_FK" FOREIGN KEY ("NURSE_ST_ID")
	  REFERENCES "NURSE_STATION" ("NURSE_ST_ID") ENABLE;
  ALTER TABLE "CONSULTATION" ADD CONSTRAINT "P_REG_ID_CONS_FK" FOREIGN KEY ("P_REG_ID")
	  REFERENCES "PATIENTS_REG_INFO" ("P_REG_ID") ENABLE;

  ALTER TABLE "CONSULT_DTL" ADD CONSTRAINT "CONSULT_ID_IN_DTL_FK" FOREIGN KEY ("CONSULTATION_ID")
	  REFERENCES "CONSULTATION" ("CONSULTATION_ID") ENABLE;

  ALTER TABLE "CONSULT_INV_DETAILS" ADD CONSTRAINT "CONSULT_ID_INV_FK" FOREIGN KEY ("CONSULTATION_ID")
	  REFERENCES "CONSULTATION" ("CONSULTATION_ID") ENABLE;
  ALTER TABLE "CONSULT_INV_DETAILS" ADD CONSTRAINT "INV_ID_FK" FOREIGN KEY ("INV_ID")
	  REFERENCES "INVESTIGATION_INFO" ("INV_ID") ENABLE;

  ALTER TABLE "CONSULT_MEDICINE_DETAILS" ADD CONSTRAINT "CONSULT_ID_IN_PRES_M_D_FK" FOREIGN KEY ("CONSULTATION_ID")
	  REFERENCES "CONSULTATION" ("CONSULTATION_ID") ENABLE;
  ALTER TABLE "CONSULT_MEDICINE_DETAILS" ADD CONSTRAINT "MC_ID_CONS_M_D_FK" FOREIGN KEY ("MED_ID")
	  REFERENCES "MEDICINE_INFO" ("MED_ID") ENABLE;

  ALTER TABLE "CONS_ADVICE_DETAILS" ADD CONSTRAINT "ADV_IDIN_CONS_ADV_FK" FOREIGN KEY ("ADV_ID")
	  REFERENCES "ADVICE_INFO" ("ADV_ID") ENABLE;
  ALTER TABLE "CONS_ADVICE_DETAILS" ADD CONSTRAINT "CONS_IDIN_ADV_FK" FOREIGN KEY ("CONSULTATION_ID")
	  REFERENCES "CONSULTATION" ("CONSULTATION_ID") ENABLE;

  ALTER TABLE "DISEASE_MEDICINE" ADD CONSTRAINT "FK_MED" FOREIGN KEY ("MED_ID")
	  REFERENCES "MEDICINE_INFO" ("MED_ID") ENABLE;

  ALTER TABLE "DISTRICTS" ADD CONSTRAINT "DIV_NO_IN_DIST_FK" FOREIGN KEY ("DIV_NO")
	  REFERENCES "DIVISIONS" ("DIV_NO") ENABLE;

   COMMENT ON TABLE "DISTRICTS_ERR$"  IS 'DML Error Logging table for "DISTRICTS"';

  ALTER TABLE "DOCS_AV_DAY" ADD CONSTRAINT "DOC_ID_INAV_DAYS_FK" FOREIGN KEY ("DOC_ID")
	  REFERENCES "DOCTORS_INFO" ("DOC_ID") ENABLE;

  ALTER TABLE "DOCTORS_DTL_INFO" ADD CONSTRAINT "DD_ID_IN_DOC_DTL_FK" FOREIGN KEY ("DD_ID")
	  REFERENCES "DR_DEGREES_INFO" ("DD_ID") ENABLE;
  ALTER TABLE "DOCTORS_DTL_INFO" ADD CONSTRAINT "DOC_ID_IN_DOC_DTL_FK" FOREIGN KEY ("DOC_ID")
	  REFERENCES "DOCTORS_INFO" ("DOC_ID") ENABLE;

  ALTER TABLE "DOCTORS_INFO" ADD CONSTRAINT "DEPT_ID_IN_DOC_FK" FOREIGN KEY ("DEPT_ID")
	  REFERENCES "DEPARTMENTS_INFO" ("DEPT_ID") ENABLE;
  ALTER TABLE "DOCTORS_INFO" ADD CONSTRAINT "DG_ID_IN_DOC_FK" FOREIGN KEY ("DG_ID")
	  REFERENCES "DESIGNATIONS_INFO" ("DG_ID") ENABLE;

  ALTER TABLE "DOCTOR_SHIFT_DTL" ADD CONSTRAINT "DOC_ID_INDOC_SH_DTL_FK" FOREIGN KEY ("DOC_ID")
	  REFERENCES "DOCTORS_INFO" ("DOC_ID") ENABLE;
  ALTER TABLE "DOCTOR_SHIFT_DTL" ADD CONSTRAINT "SH_ID_IN_DOC_SH_DTL_FK" FOREIGN KEY ("SH_ID")
	  REFERENCES "SHIFTS_INFO" ("SH_ID") ENABLE;

  ALTER TABLE "DOC_EXP_DTL" ADD CONSTRAINT "DOC_ID_IN_DOC_EXP_FK" FOREIGN KEY ("DOC_ID")
	  REFERENCES "DOCTORS_INFO" ("DOC_ID") ENABLE;

  ALTER TABLE "DOC_SERVICES" ADD CONSTRAINT "DOC_ID_IN_DOC_SERVICE" FOREIGN KEY ("DOC_ID")
	  REFERENCES "DOCTORS_INFO" ("DOC_ID") ENABLE;
  ALTER TABLE "DOC_SERVICES" ADD CONSTRAINT "SERVICE_INDOC_SERVICE" FOREIGN KEY ("SERVICE_ID")
	  REFERENCES "SERVICES" ("SERVICE_ID") ENABLE;

  ALTER TABLE "EMPLOYEES_INFO" ADD CONSTRAINT "DEPT_ID_IN_EMP_FK" FOREIGN KEY ("DEPT_ID")
	  REFERENCES "DEPARTMENTS_INFO" ("DEPT_ID") ENABLE;
  ALTER TABLE "EMPLOYEES_INFO" ADD CONSTRAINT "DG_ID_IN_EMP_FK" FOREIGN KEY ("DG_ID")
	  REFERENCES "DESIGNATIONS_INFO" ("DG_ID") ENABLE;

  ALTER TABLE "EMPLOYEE_SHIFT_DTL" ADD CONSTRAINT "EMP_ID_IN_EMP_SH_FK" FOREIGN KEY ("EMP_ID")
	  REFERENCES "EMPLOYEES_INFO" ("EMP_ID") ENABLE;
  ALTER TABLE "EMPLOYEE_SHIFT_DTL" ADD CONSTRAINT "SH_ID_IN_EMP_SH_DTL_FK" FOREIGN KEY ("SH_ID")
	  REFERENCES "SHIFTS_INFO" ("SH_ID") ENABLE;

  ALTER TABLE "GROUP_MENU" ADD CONSTRAINT "UI_GR_ID_FK" FOREIGN KEY ("GROUP_ID")
	  REFERENCES "USER_GROUP" ("USER_GROUP_ID") ENABLE;

  ALTER TABLE "MEDICINE_INFO" ADD CONSTRAINT "GEN_ID_GEN_INFO_FK" FOREIGN KEY ("GENERIC_ID")
	  REFERENCES "GENERIC_INFO" ("GENERIC_ID") ENABLE;

  ALTER TABLE "NURSE_STATION" ADD CONSTRAINT "APP_ID_IN_NURSE_ST_FK" FOREIGN KEY ("APP_ID")
	  REFERENCES "APPOINTMENT_INFO" ("APP_ID") ENABLE;

  ALTER TABLE "PRIMARY_ASSESSMENT" ADD CONSTRAINT "NURSE_ST_IN_PR_A_FK" FOREIGN KEY ("NURSE_ST_ID")
	  REFERENCES "NURSE_STATION" ("NURSE_ST_ID") ENABLE;

  ALTER TABLE "PS_UPAZILAS" ADD CONSTRAINT "DIST_NO_IN_PS_FK" FOREIGN KEY ("DIST_NO")
	  REFERENCES "DISTRICTS" ("DIST_NO") ENABLE;

  ALTER TABLE "UNIONS" ADD CONSTRAINT "PS_UPAZILA_IN_UNI_FK" FOREIGN KEY ("PS_UPAZILA_NO")
	  REFERENCES "PS_UPAZILAS" ("PS_UPAZILA_NO") ENABLE;

  ALTER TABLE "USERS_INFO" ADD CONSTRAINT "EMP_ID_IN_UI_FK" FOREIGN KEY ("EMP_ID")
	  REFERENCES "EMPLOYEES_INFO" ("EMP_ID") ENABLE;
  ALTER TABLE "USERS_INFO" ADD CONSTRAINT "RI_ID_IN_UI_FK" FOREIGN KEY ("RI_ID")
	  REFERENCES "ROLES_INFO" ("RI_ID") ENABLE;
create or replace FUNCTION  "GET_AGE" (p_DOB date) return varchar2 
is 
BEGIN 
return (ABS(ROUND(MONTHS_BETWEEN(SYSDATE, p_DOB)/12)))||'Year'; 
end;
/
create or replace FUNCTION  "GET_CL_FULL_ADDRESS" ( 
    p_cl_id IN NUMBER 
) RETURN VARCHAR2 IS 
    v_address VARCHAR2(1000); 
    v_union_name VARCHAR2(1000); 
    v_ps_upazila_name VARCHAR2(1000); 
    v_dist_name VARCHAR2(1000); 
    v_div_name VARCHAR2(1000); 
    v_full_address VARCHAR2(4000); 
BEGIN 
    -- Fetch patient address and keys from the patient_table 
    SELECT address, union_no, ps_upazila_no, dist_no, div_no 
    INTO v_address, v_union_name, v_ps_upazila_name, v_dist_name, v_div_name 
    FROM clinic_INFO 
    WHERE clinic_id = p_cl_id; 
 
    -- Fetch union name 
    SELECT union_name 
    INTO v_union_name 
    FROM unions 
    WHERE union_no = v_union_name; 
 
    -- Fetch ps_upazila name 
    SELECT ps_upazila_name 
    INTO v_ps_upazila_name 
    FROM ps_upazilas 
    WHERE ps_upazila_no = v_ps_upazila_name; 
 
    -- Fetch district name 
    SELECT dist_name 
    INTO v_dist_name 
    FROM districts 
    WHERE dist_no = v_dist_name; 
 
    -- Fetch division name 
    SELECT div_name 
    INTO v_div_name 
    FROM divisions 
    WHERE div_no = v_div_name; 
 
    -- Concatenate to create full address 
    v_full_address := v_address || ', ' || v_union_name || ', ' || v_ps_upazila_name || ', ' || v_dist_name || ', ' || v_div_name; 
 
    RETURN v_full_address; 
END;
/
create or replace function get_dept(p_dept_id number) return varchar2 is
v_dept varchar2(100);
begin
select dept_name into v_dept
from departments_info
where dept_id =p_dept_id;
return v_dept;
end;
/
create or replace FUNCTION  "GET_FULL_ADDRESS" ( 
    p_reg_id IN NUMBER 
) RETURN VARCHAR2 IS 
    v_full_address VARCHAR2(4000); 
BEGIN 
    SELECT  
        p.address || ', ' || u.union_name || ', ' || p.ps_upazila_name || ', ' || dist.dist_name || ', ' || d.div_name 
    INTO  
        v_full_address 
    FROM  
    PATIENTS_REG_INFO p 
    join 
        unions u       ON p.address= p_address 
    JOIN  
        ps_upazilas p ON p.ps_upazila_no = p_ps_upazila_no 
    JOIN  
        districts dist ON dist.dist_no = p_dist_no 
    JOIN  
        divisions d ON d.div_no = p_div_no 
    WHERE  
        u.union_no = p_union_no; 
 
    RETURN v_full_address; 
END;
/
create or replace FUNCTION get_full_age(p_dob DATE) 
    RETURN VARCHAR2 
IS
    v_years NUMBER;
    v_months NUMBER;
    v_days NUMBER;
    v_result VARCHAR2(100);
BEGIN
    -- Calculate the number of years, months, and days
    SELECT FLOOR(MONTHS_BETWEEN(SYSDATE, p_dob) / 12),  -- Years
           FLOOR(MOD(MONTHS_BETWEEN(SYSDATE, p_dob), 12)),  -- Months
           TRUNC(SYSDATE) - ADD_MONTHS(p_dob, FLOOR(MONTHS_BETWEEN(SYSDATE, p_dob) / 12) * 12)  -- Days
    INTO v_years, v_months, v_days
    FROM dual;
    
    -- Combine the result into a single string
    v_result := v_years || ' years, ' || v_months || ' months, ' || v_days || ' days';
    
    RETURN v_result;
END get_full_age;
/
create or replace FUNCTION  "GET_PATIENT_FULL_ADDRESS" ( 
    p_reg_id IN NUMBER 
) RETURN VARCHAR2 IS 
    v_address VARCHAR2(1000); 
    v_union_name VARCHAR2(1000); 
    v_ps_upazila_name VARCHAR2(1000); 
    v_dist_name VARCHAR2(1000); 
    v_div_name VARCHAR2(1000); 
    v_full_address VARCHAR2(4000); 
BEGIN 
    -- Fetch patient address and keys from the patient_table 
    SELECT address, union_no, ps_upazila_no, dist_no, div_no 
    INTO v_address, v_union_name, v_ps_upazila_name, v_dist_name, v_div_name 
    FROM PATIENTS_REG_INFO 
    WHERE p_reg_id = p_reg_id; 
 
    -- Fetch union name 
    SELECT union_name 
    INTO v_union_name 
    FROM unions 
    WHERE union_no = v_union_name; 
 
    -- Fetch ps_upazila name 
    SELECT ps_upazila_name 
    INTO v_ps_upazila_name 
    FROM ps_upazilas 
    WHERE ps_upazila_no = v_ps_upazila_name; 
 
    -- Fetch district name 
    SELECT dist_name 
    INTO v_dist_name 
    FROM districts 
    WHERE dist_no = v_dist_name; 
 
    -- Fetch division name 
    SELECT div_name 
    INTO v_div_name 
    FROM divisions 
    WHERE div_no = v_div_name; 
 
    -- Concatenate to create full address 
    v_full_address := v_address || ', ' || v_union_name || ', ' || v_ps_upazila_name || ', ' || v_dist_name || ', ' || v_div_name; 
 
    RETURN v_full_address; 
END;
/
create or replace FUNCTION  "SPELL_OUT" (a_number NUMBER)  
RETURN VARCHAR2 IS 
    TYPE numtab IS TABLE OF VARCHAR2(30) 
        INDEX BY BINARY_INTEGER; 
    number_chart numtab; 
    crore NUMBER; 
    lakh NUMBER; 
    thou NUMBER; 
    hund NUMBER; 
    doubl NUMBER; 
    sing NUMBER; 
    deci NUMBER; 
    text VARCHAR2(500); 
BEGIN 
    -- Initialize the number chart 
    number_chart(1) := 'One'; 
    number_chart(2) := 'Two'; 
    number_chart(3) := 'Three'; 
    number_chart(4) := 'Four'; 
    number_chart(5) := 'Five'; 
    number_chart(6) := 'Six'; 
    number_chart(7) := 'Seven'; 
    number_chart(8) := 'Eight'; 
    number_chart(9) := 'Nine'; 
    number_chart(10) := 'Ten'; 
    number_chart(11) := 'Eleven'; 
    number_chart(12) := 'Twelve'; 
    number_chart(13) := 'Thirteen'; 
    number_chart(14) := 'Fourteen'; 
    number_chart(15) := 'Fifteen'; 
    number_chart(16) := 'Sixteen'; 
    number_chart(17) := 'Seventeen'; 
    number_chart(18) := 'Eighteen'; 
    number_chart(19) := 'Nineteen'; 
    number_chart(20) := 'Twenty'; 
    number_chart(30) := 'Thirty'; 
    number_chart(40) := 'Forty'; 
    number_chart(50) := 'Fifty'; 
    number_chart(60) := 'Sixty'; 
    number_chart(70) := 'Seventy'; 
    number_chart(80) := 'Eighty'; 
    number_chart(90) := 'Ninety'; 
 
    -- Break down the number 
    crore := FLOOR(a_number / 10000000); 
    lakh := FLOOR(MOD(a_number, 10000000) / 100000); 
    thou := FLOOR(MOD(a_number, 100000) / 1000); 
    hund := FLOOR(MOD(a_number, 1000) / 100); 
    doubl := FLOOR(MOD(a_number, 100) / 10) * 10; 
    sing := MOD(a_number, 10); 
    deci := ROUND((a_number - TRUNC(a_number)) * 100); 
 
    -- Initialize the text variable 
    text := ''; 
 
    -- Add crore part 
    IF crore <> 0 THEN 
        text := text || number_chart(crore) || ' Crore '; 
    END IF; 
 
    -- Add lakh part 
    IF lakh <> 0 THEN 
        IF lakh <= 20 OR lakh MOD 10 = 0 THEN 
            text := text || number_chart(lakh) || ' Lakh '; 
        ELSE 
            text := text || number_chart(lakh - lakh MOD 10) || ' ' || number_chart(lakh MOD 10) || ' Lakh '; 
        END IF; 
    END IF; 
 
    -- Add thousand part 
    IF thou <> 0 THEN 
        IF thou <= 20 OR thou MOD 10 = 0 THEN 
            text := text || number_chart(thou) || ' Thousand '; 
        ELSE 
            text := text || number_chart(thou - thou MOD 10) || ' ' || number_chart(thou MOD 10) || ' Thousand '; 
        END IF; 
    END IF; 
 
    -- Add hundred part 
    IF hund <> 0 THEN 
        IF hund <= 20 OR hund MOD 10 = 0 THEN 
            text := text || number_chart(hund) || ' Hundred '; 
        ELSE 
            text := text || number_chart(hund - hund MOD 10) || ' ' || number_chart(hund MOD 10) || ' Hundred '; 
        END IF; 
    END IF; 
 
    -- Add tens and ones part 
    IF doubl <> 0 THEN 
        IF doubl <= 20 OR doubl MOD 10 = 0 THEN 
            text := text || number_chart(doubl) || ' '; 
        ELSE 
            text := text || number_chart(doubl) || ' ' || number_chart(sing) || ' '; 
        END IF; 
    END IF; 
 
    -- Add paisa part (decimal handling) 
    IF deci > 0 THEN 
        IF deci <= 20 OR deci MOD 10 = 0 THEN 
            text := text || 'and ' || number_chart(deci) || ' Paisa '; 
        ELSE 
            text := text || 'and ' || number_chart(deci - deci MOD 10) || ' ' || number_chart(deci MOD 10) || ' Paisa '; 
        END IF; 
    END IF; 
 
    -- Return the text with "Only" 
    IF text IS NOT NULL THEN 
        RETURN text || 'Only'; 
    ELSE 
        RETURN 'Zero Only'; 
    END IF; 
END SPELL_OUT;
/






















































































































  CREATE UNIQUE INDEX "ADVV_ID_PK" ON "ADVICE_INFO" ("ADV_ID") 
  ;

  CREATE UNIQUE INDEX "APP_ID_NU_ST_UQ" ON "NURSE_STATION" ("APP_ID") 
  ;

  CREATE UNIQUE INDEX "APP_ID_PK" ON "APPOINTMENT_INFO" ("APP_ID") 
  ;

  CREATE UNIQUE INDEX "APP_SYS_NAV_PK" ON "APP_SYS_NAV" ("NAV_NO") 
  ;

  CREATE UNIQUE INDEX "ASSESS_ID_CONS_UQ" ON "CONSULTATION" ("ASSESSMENT_ID") 
  ;

  CREATE UNIQUE INDEX "BILLING_ID_PK" ON "BILLING" ("BILL_ID") 
  ;

  CREATE UNIQUE INDEX "CI_ID_PK" ON "CLINIC_INFO" ("CLINIC_ID") 
  ;

  CREATE UNIQUE INDEX "CONSULT_ID_PK" ON "CONSULTATION" ("CONSULTATION_ID") 
  ;

  CREATE UNIQUE INDEX "CONS_ADV_DTL_ID_PK" ON "CONS_ADVICE_DETAILS" ("CONSULT_ADV_DTL_ID") 
  ;

  CREATE UNIQUE INDEX "CONS_DTL_PK" ON "CONSULT_DTL" ("CONSULT_DTL_ID") 
  ;

  CREATE UNIQUE INDEX "DD_ID_PK" ON "DR_DEGREES_INFO" ("DD_ID") 
  ;

  CREATE UNIQUE INDEX "DEPT_ID_PK" ON "DEPARTMENTS_INFO" ("DEPT_ID") 
  ;

  CREATE UNIQUE INDEX "DG_ID_PK" ON "DESIGNATIONS_INFO" ("DG_ID") 
  ;

  CREATE UNIQUE INDEX "DISEASE_PK" ON "DISEASE" ("DIS_ID") 
  ;

  CREATE UNIQUE INDEX "DIST_NO_PK" ON "DISTRICTS" ("DIST_NO") 
  ;

  CREATE UNIQUE INDEX "DIV_NO_PK" ON "DIVISIONS" ("DIV_NO") 
  ;

  CREATE UNIQUE INDEX "DOC_DAY_PK" ON "DOCS_AV_DAY" ("DOC_DAYS") 
  ;

  CREATE UNIQUE INDEX "DOC_ID_PK" ON "DOCTORS_INFO" ("DOC_ID") 
  ;

  CREATE UNIQUE INDEX "DOC_SERVICE_PK" ON "DOC_SERVICES" ("DOC_SERVICE_ID") 
  ;

  CREATE UNIQUE INDEX "DOC_SH_ID_PK" ON "DOCTOR_SHIFT_DTL" ("DOC_SH_ID") 
  ;

  CREATE UNIQUE INDEX "DR_SH_PK_NEW" ON "DR_NEW_SHIFT_INFO" ("DR_SH_ID") 
  ;

  CREATE UNIQUE INDEX "DTL_ID_PK" ON "DOCTORS_DTL_INFO" ("DTL_ID") 
  ;

  CREATE UNIQUE INDEX "EMP_ID_PK" ON "EMPLOYEES_INFO" ("EMP_ID") 
  ;

  CREATE UNIQUE INDEX "EMP_SH_ID_PK" ON "EMPLOYEE_SHIFT_DTL" ("EMP_SH_ID") 
  ;

  CREATE UNIQUE INDEX "GEN_ID_PK" ON "GENERIC_INFO" ("GENERIC_ID") 
  ;

  CREATE UNIQUE INDEX "GROUP_MENU_ID_PK" ON "GROUP_MENU" ("GROUP_MENU_ID") 
  ;

  CREATE UNIQUE INDEX "GROUP_PK" ON "GROUPS" ("GROUP_ID") 
  ;

  CREATE UNIQUE INDEX "INV_ID_PK" ON "INVESTIGATION_INFO" ("INV_ID") 
  ;

  CREATE UNIQUE INDEX "MED_DET_ID_PK" ON "CONSULT_MEDICINE_DETAILS" ("MED_DETAIL_ID") 
  ;

  CREATE UNIQUE INDEX "MED_ID_PK" ON "MEDICINE_INFO" ("MED_ID") 
  ;

  CREATE UNIQUE INDEX "MENU_MENU_APEX_MENU_UK" ON "MENU" ("MENU_CODE", "APEX_PAGE_NO") 
  ;

  CREATE UNIQUE INDEX "MENU_MENU_CODE_PK" ON "MENU" ("MENU_CODE") 
  ;

  CREATE UNIQUE INDEX "MOBILE_NO_UK" ON "EMPLOYEES_INFO" ("MOBILE_NO") 
  ;

  CREATE UNIQUE INDEX "MOB_NO_UK" ON "DOCTORS_INFO" ("MOBILE_NO") 
  ;

  CREATE UNIQUE INDEX "NURSE_ST_ID_PK" ON "NURSE_STATION" ("NURSE_ST_ID") 
  ;

  CREATE UNIQUE INDEX "NU_ST_IDIN_PR_AS_UQ" ON "PRIMARY_ASSESSMENT" ("NURSE_ST_ID") 
  ;

  CREATE UNIQUE INDEX "PRES_INV_DE_ID_PK" ON "CONSULT_INV_DETAILS" ("CONSULT_INV_DTL_ID") 
  ;

  CREATE UNIQUE INDEX "PS_UPAZILA_NO_PK" ON "PS_UPAZILAS" ("PS_UPAZILA_NO") 
  ;

  CREATE UNIQUE INDEX "P_A_ID_PK" ON "PRIMARY_ASSESSMENT" ("ASSESSMENT_ID") 
  ;

  CREATE UNIQUE INDEX "P_REG_ID_PK" ON "PATIENTS_REG_INFO" ("P_REG_ID") 
  ;

  CREATE UNIQUE INDEX "RI_ID_PK" ON "ROLES_INFO" ("RI_ID") 
  ;

  CREATE UNIQUE INDEX "SERVICE_ID_PK" ON "SERVICES" ("SERVICE_ID") 
  ;

  CREATE UNIQUE INDEX "SH_ID_PK" ON "SHIFTS_INFO" ("SH_ID") 
  ;

  CREATE UNIQUE INDEX "UI_ID_PK" ON "USERS_INFO" ("UI_ID") 
  ;

  CREATE UNIQUE INDEX "UNION_NO_PK" ON "UNIONS" ("UNION_NO") 
  ;

  CREATE UNIQUE INDEX "USERNAME_UK" ON "USERS_INFO" ("USERNAME") 
  ;

  CREATE UNIQUE INDEX "USER_GROUP_ID_PK" ON "USER_GROUP" ("USER_GROUP_ID") 
  ;

  CREATE UNIQUE INDEX "USER_LOG_NO_PK" ON "USER_SESSION_TRACKING" ("LOG_NO") 
  ;























































create or replace PACKAGE EMR_pkg AS
  FUNCTION GET_MED(P_MED_ID NUMBER) RETURN VARCHAR2;

   FUNCTION GET_INV(P_INV_ID NUMBER) RETURN VARCHAR2;

 FUNCTION GET_ADV(P_ADV_ID NUMBER) RETURN VARCHAR2;
 FUNCTION GET_DOC(P_DOC_ID NUMBER) RETURN VARCHAR2;
  FUNCTION GET_PAT(P_PREG_ID NUMBER) RETURN VARCHAR2;
    FUNCTION GET_SCH(P_DOC_ID NUMBER) RETURN VARCHAR2;
END EMR_pkg;
/




























































































































create or replace PROCEDURE google_user_map
IS
    l_email   VARCHAR2(255);
    l_user    VARCHAR2(100);
BEGIN
    -- Email returned by Google
    l_email := lower(apex_util.get_session_state('APEX$AUTHENTICATION_EMAIL'));

    SELECT USER_NAME
    INTO   l_user
    FROM   guser
    WHERE  lower(email) = l_email;

    -- Switch to mapped APEX user
    apex_authentication.login(
        p_username => l_user
    );

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        raise_application_error(
            -20001,
            'Your Google account is not linked to any application user.'
        );
END;
/
create or replace PROCEDURE post_auth_context
IS
    l_user_name VARCHAR2(100);
    l_user_id   NUMBER;
    l_group_id  NUMBER;
BEGIN
    -- Get the authenticated APEX username
    l_user_name := v('APP_USER');  -- THIS WORKS IN Post-Authentication Procedure

    -- Get USER_ID
    SELECT user_id
    INTO   l_user_id
    FROM   GUSER
    WHERE  UPPER(user_name) = UPPER(l_user_name);

    -- Get GROUP_ID
    SELECT group_id
    INTO   l_group_id
    FROM   USER_GROUP
    WHERE  user_id = l_user_id;

    -- Set values to session items
    apex_util.set_session_state('SESSION_GROUP_ID', l_user_id);
    apex_util.set_session_state('G_USER_GRP', l_group_id);

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        NULL;
END;
/
create or replace PROCEDURE post_auth_context2
IS
    l_user_name VARCHAR2(100);
    l_user_id   NUMBER;
    l_group_id  NUMBER;
BEGIN
    -- Determine username
    IF :P9999_USERNAME IS NOT NULL THEN
        -- Normal login
        l_user_name := :P9999_USERNAME;
    ELSE
        -- Google login
        l_user_name := :APP_USER;  -- returned by Google
    END IF;

    -- Get USER_ID
    SELECT user_id
    INTO   l_user_id
    FROM   GUSER
    WHERE  UPPER(user_name) = UPPER(l_user_name);

    -- Get GROUP_ID
    SELECT group_id
    INTO   l_group_id
    FROM   USER_GROUP
    WHERE  user_id = l_user_id;

    -- Set session items
    apex_util.set_session_state('SESSION_GROUP_ID', l_user_id);
    apex_util.set_session_state('G_USER_GRP', l_group_id);

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        NULL;
END;
/
create or replace PROCEDURE  "PRC_PRESCRIBE_MEDICINES" ( 
    P_CONSULTATION_ID IN NUMBER,  -- Consultation for which medicines are prescribed 
    P_DISEASE_id IN number  -- Disease name to fetch medicines 
  --  P_DOC_ID IN NUMBER            -- Doctor prescribing the medicine 
) 
AS 
    -- Cursor to get medicines related to the disease 
    CURSOR CUR_MEDICINES IS 
    SELECT M.MED_ID, M.MED_NAME , 
DP.FREQUENCY, DP.INTAKE_DAYS 
FROM DISEASE_MEDICINE DP  
       JOIN DISEASE D   
       ON (DP.DIS_id = D.DIS_ID) 
        JOIN MEDICINE_info M  ON (M.MED_ID = DP.MED_ID) 
        where dp.dis_id=P_DISEASE_id; 
    -- Variables to hold medicine details 
    V_MED_ID NUMBER; 
    V_MED_NAME VARCHAR2(100); 
    V_INTAKE_DAYS NUMBER; 
    V_FREQUENCY VARCHAR2(50); 
    V_SL_NO NUMBER; 
 
BEGIN 
    -- Loop through all medicines for the selected disease 
    FOR REC IN CUR_MEDICINES LOOP 
        -- Get the next sequence number for the prescription entry 
        SELECT NVL(MAX(SL_NO), 0) + 1 INTO V_SL_NO FROM consult_medicine_details WHERE CONSULTATION_ID = P_CONSULTATION_ID; 
 
        -- Insert into the prescribed medicine table 
        INSERT INTO consult_medicine_details (SL_NO, CONSULTATION_ID) 
        VALUES (V_SL_NO, P_CONSULTATION_ID); 
 
        -- Insert into the medicine details table with dosage information 
        INSERT INTO consult_medicine_details (MED_DETAIL_ID, MED_ID, CONSULTATION_ID, INTAKE_DAYS, FREQUENCY) 
        VALUES (SEQ_MED_DETAIL.NEXTVAL, REC.MED_ID, P_CONSULTATION_ID, REC.INTAKE_DAYS, REC.FREQUENCY); 
    END LOOP; 
 
    -- Commit the transaction 
    COMMIT; 
 
    --DBMS_OUTPUT.PUT_LINE('Medicines prescribed successfully for disease: ' || P_DISEASE_id); 
 
EXCEPTION 
    WHEN OTHERS THEN 
        ROLLBACK; 
        DBMS_OUTPUT.PUT_LINE('Error: ' || SQLERRM); 
END PRC_PRESCRIBE_MEDICINES;
/

































































   CREATE SEQUENCE  "ASSESS_PK_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 100369 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

   CREATE SEQUENCE  "CONS_ADV_DTL_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 10000 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

   CREATE SEQUENCE  "CONS_INV_DTL_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 10300 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

   CREATE SEQUENCE  "CONS_MED_DTL_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1000351 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "BILLINGVIEW" ("APP_SERIAL_NO", "APP_MOBILE_NO", "P_NAME", "DOC_NAME", "SHIFT_NAME", "APP_ID", "START_TIME", "END_TIME", "X", "DOC_ID", "PATIENT_TYPE", "NURSE_ST_ID") AS 
  SELECT A. APP_SERIAL_NO, A.APP_MOBILE_NO,  P.P_NAME,D.DOC_NAME, DS.SHIFT_NAME, A.APP_ID, DS.START_TIME, DS.END_TIME,NULL AS X,D.DOC_ID, 
A.PATIENT_TYPE,N.NURSE_ST_ID 
FROM APPOINTMENT_INFO A JOIN PATIENTS_REG_INFO P 
ON(A.P_REG_ID = P.P_REG_ID) 
JOIN DOCTORS_INFO D 
ON(A.DOC_ID = D.DOC_ID) 
JOIN  DR_NEW_SHIFT_INFO DS 
ON(D.DR_SH_ID =DS.DR_SH_ID) 
JOIN NURSE_STATION N 
ON(A.APP_ID = N.APP_ID) 
WHERE --A.APP_DATE_TIME = trim(SYSDATE) AND
 NVL(N.BILLING_FLAG,'N')<>'P';

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "CONSULTAION_LOV" ("APP_ID", "P_NAME", "P_REG_ID", "NURSE_ST_ID", "VISIT_DATE") AS 
  (SELECT A.app_id, P.P_NAME, p.p_reg_id, N.NURSE_ST_ID, N.VISIT_DATE 
FROM Nurse_station N JOIN APPOINTMENT_INFO A 
ON(N.APP_ID = A.APP_ID) 
 JOIN PATIENTS_REG_INFO P  
ON(A.P_REG_ID = P.P_REG_ID)) 
--where TO_CHAR(N.visit_date,'DD-MON-RR') = to_char(sysdate,'DD-MON-RR')) 
order by 1 asc;

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "DOC_COMPLETED_LIST" ("CONSULTATION_ID", "NURSE_ST_ID", "DOC_ID", "APP_SERIAL_NO", "DOC_NAME", "VISIT_DATE", "APP_ID", "P_NAME", "CONSULT_FLAG", "PATIENT_TYPE", "RATE", "OUT_FLAG") AS 
  select C.CONSULTATION_ID,N.nurse_st_id , a.doc_id,a.app_serial_no,d.doc_name, n.visit_date,a.app_id, 
p.p_name, n.consult_flag, a.patient_type,ds.rate, n.out_flag 
from CONSULTATION C 
JOIN nurse_station n  
ON C.APP_ID= N.APP_ID 
join appointment_info a 
on(n.app_id= a.app_id) 
join patients_reg_info p 
on(a.p_reg_id = p.p_reg_id) 
join doctors_info d 
on(d.doc_id= a.doc_id) 
join DOC_SERVICES ds 
on(ds.patient_type = a.patient_type) 
where -- TRUNC(n.visit_date)= trunc(sysdate) 
---and
 NVL(n.Consult_flag,'N') = 'Y' 
AND NVL(n.OUT_FLAG,'N')='Y' 
and (ds.doc_id = a.doc_id);

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "DOC_WAITING_LIST" ("NURSE_ST_ID", "APP_SERIAL_NO", "DOC_ID", "DOC_NAME", "VISIT_DATE", "APP_ID", "P_NAME", "PATIENT_TYPE", "CONSULT_FLAG", "STATUS_VITAL_SIGN", "OUT_FLAG") AS 
  select n.nurse_st_id,a.app_serial_no, a.doc_id,d.doc_name, n.visit_date,a.app_id, 
p.p_name, a.patient_type, n.consult_flag,n.status_vital_sign ,n.out_flag 
from nurse_station n join appointment_info a 
on(n.app_id= a.app_id) 
join patients_reg_info p 
on(a.p_reg_id = p.p_reg_id) 
join doctors_info d 
on(d.doc_id= a.doc_id) 
where --TRUNC(n.visit_date)= trunc(sysdate) 
--And
 n.STATUS_VITAL_SIGN = 'Completed' 
and NVL(n.Consult_flag,'N') = 'Y'  
AND NVL(n.OUT_FLAG,'N')='N';

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "NURSE_STAION" ("APP_SERIAL_NO", "APP_MOBILE_NO", "P_NAME", "DOC_NAME", "SHIFT_NAME", "APP_ID", "START_TIME", "END_TIME", "X", "APP_DATE_TIME") AS 
  SELECT A.APP_SERIAL_NO, A.APP_MOBILE_NO, P.P_NAME, D.DOC_NAME, DS.SHIFT_NAME, A.APP_ID, DS.START_TIME, DS.END_TIME, NULL AS X, A.APP_DATE_TIME 
   FROM APPOINTMENT_INFO A 
   JOIN PATIENTS_REG_INFO P ON A.P_REG_ID = P.P_REG_ID 
   JOIN DOCTORS_INFO D ON A.DOC_ID = D.DOC_ID 
   JOIN DR_NEW_SHIFT_INFO DS ON D.DR_SH_ID = DS.DR_SH_ID 
   WHERE ----(a.APP_DATE_TIME = trim(sysdate+1)
  ----- or a.APP_DATE_TIME = trim(sysdate))
   --OR APP_DATE_TIME = TRIM(SYSDATE + 1)) 
   A.APP_ID NOT IN (SELECT APP_ID FROM NURSE_STATION WHERE APP_ID IS NOT NULL);

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "PRE_CONSULT_INFO" ("NURSE_ST_ID", "VISIT_DATE", "APP_ID", "P_REG_ID", "P_NAME", "GENDER", "AGE", "BLOOD_GROUP", "DOC_ID", "DETAILS", "DOC_NAME", "DEPT_NAME", "BP", "RR", "H_RATE", "TEMP", "HEIGHT", "WEIGHT", "CHIEF_COMPLAINS", "ASSESSMENT_ID") AS 
  SELECT N.nurse_st_id, N.VISIT_DATE,A.app_id, p.p_reg_id, P.P_NAME, P.GENDER, get_age(P.DATE_OF_BIRTH) AGE, p.blood_group,D.DOC_ID,D.DETAILS, D.DOC_NAME, DD.depT_name, 
pa.BP, PA.RR, PA.h_RATE, PA.TEMP, PA.HEIGHT,PA.WEIGHT, PA.CHIEF_COMPLAINS,PA.ASSESSMENT_ID   
 
FROM Nurse_station N, APPOINTMENT_INFO A,PATIENTS_REG_INFO P,  DOCTORS_INFO D, DEPARTMENTS_INFO DD, PRIMARY_ASSESSMENT PA 
 
WHERE   
(N.APP_ID = A.APP_ID) 
AND (N.NURSE_ST_ID = PA.NURSE_ST_ID) 
AND 
(A.P_REG_ID = P.P_REG_ID) 
AND 
(A.DOC_ID = D.DOC_ID) 
AND(D.DEPT_ID = DD.DEPT_ID);

   COMMENT ON TABLE "DISTRICTS_ERR$"  IS 'DML Error Logging table for "DISTRICTS"';























































create or replace PACKAGE BODY EMR_pkg AS
FUNCTION GET_MED(P_MED_ID NUMBER) RETURN VARCHAR2 IS
v_MED VARCHAR2(100);
BEGIN
SELECT MED_NAME INTO V_MED
FROM MEDICINE_INFO
WHERE MED_ID= P_MED_ID;
RETURN V_MED;
END;

FUNCTION GET_INV(P_INV_ID NUMBER) RETURN VARCHAR2 IS
v_INV VARCHAR2(100);
BEGIN
SELECT INV_NAME INTO V_INV
FROM INVESTIGATION_INFO
WHERE INV_ID= P_INV_ID;
RETURN V_INV;
END;

FUNCTION GET_ADV(P_ADV_ID NUMBER) RETURN VARCHAR2 IS
v_ADV VARCHAR2(100);
BEGIN
SELECT ADV_NAME INTO V_ADV
FROM ADVICE_INFO
WHERE ADV_ID= P_ADV_ID;
RETURN V_ADV;
END;

FUNCTION GET_DOC(P_DOC_ID NUMBER) RETURN VARCHAR2 IS
v_DOC VARCHAR2(100);
BEGIN
SELECT DOC_NAME INTO V_DOC
FROM DOCTORS_INFO
WHERE DOC_ID= P_DOC_ID;
RETURN V_DOC;
END;


  FUNCTION GET_SCH(P_DOC_ID NUMBER) RETURN VARCHAR2 IS
  V_TIME VARCHAR2(100);
  BEGIN
 select   DS.shift_name||' ('|| DS.START_TIME||'-'|| DS.END_TIME||')' into v_time

  from doctors_info D, DR_NEW_SHIFT_INFO DS
	WHERE(D.DR_SH_ID = DS.DR_SH_ID)
	AND DOC_ID =p_doc_id;
RETURN V_TIME;
END;

FUNCTION GET_PAT(P_PREG_ID NUMBER) RETURN VARCHAR2 IS
V_NAME VARCHAR2(100);
BEGIN
SELECT P_NAME INTO V_NAME 
FROM PATIENTS_REG_INFO
WHERE P_REG_ID = P_PREG_ID;
RETURN V_NAME;
END;

END EMR_PKG;
/



































































 